// ═══════════════════════════════════════════════════════════════
// ALFRED — Brand System (charte officielle bowtie)
// ═══════════════════════════════════════════════════════════════
export const C = {
  // Couleurs principales (charte Alfred)
  encre: "#0F1B2D",          // Couleur principale
  champagne: "#D4A95C",      // Accent premium · CTA
  ivoire: "#F7F3EB",         // Fonds et surfaces
  emeraude: "#1F6B4A",       // Économies · gains

  // Variations
  encreLight: "#1A2A42",
  encreDeep: "#0A1320",
  champagneLight: "#E5C285",
  champagneDeep: "#A8843F",
  ivoireDeep: "#EFEADD",
  ivoireDeeper: "#E5DECC",
  emeraudeLight: "#2D8B62",

  // Système light theme
  bg: "#F7F3EB",             // ivoire
  bgPanel: "#FFFFFF",
  bgCard: "#FFFFFF",
  bgSubtle: "#FBF8F1",
  bgHover: "#F1ECE0",
  bgInput: "#FFFFFF",

  border: "rgba(15, 27, 45, 0.08)",
  borderStrong: "rgba(15, 27, 45, 0.18)",
  borderSubtle: "rgba(15, 27, 45, 0.04)",
  borderGold: "rgba(212, 169, 92, 0.4)",

  text: "#0F1B2D",           // encre
  textMuted: "#5A6478",
  textDim: "#8B92A3",

  // Statuts
  todo: "#8B92A3",
  doing: "#3B82F6",
  review: "#A855F7",
  done: "#1F6B4A",           // émeraude
  blocked: "#C73E47",
};

export const FIB_VALUES = [1, 2, 3, 5, 8, 13, 21];
export const FIB_COLORS = { 1: "#1F6B4A", 2: "#2D8B62", 3: "#84BD56", 5: "#D4A95C", 8: "#E08D3C", 13: "#D45F4A", 21: "#A82E2E" };
export const FIB_LABEL = { 1: "Trivial", 2: "Très facile", 3: "Facile", 5: "Moyen", 8: "Difficile", 13: "Très difficile", 21: "Énorme" };

export const STATUSES = [
  { id: "todo",    label: "À faire",   color: C.todo,    icon: "○" },
  { id: "doing",   label: "En cours",  color: C.doing,   icon: "◐" },
  { id: "review",  label: "En revue",  color: C.review,  icon: "◑" },
  { id: "done",    label: "Terminé",   color: C.done,    icon: "●" },
  { id: "blocked", label: "Bloqué",    color: C.blocked, icon: "✕" },
];

// ═══ MATRICE EISENHOWER — 4 quadrants ═══
export const QUADRANTS = [
  { id: "do",       label: "Urgent & Important",       short: "À faire maintenant",       color: "#C73E47", emoji: "🔥", desc: "Crise, échéance, blocant" },
  { id: "schedule", label: "Important, pas urgent",    short: "À planifier",              color: "#1F6B4A", emoji: "📅", desc: "Stratégique, à programmer" },
  { id: "delegate", label: "Urgent, pas important",    short: "À déléguer",               color: "#D4A95C", emoji: "👥", desc: "Pression mais peu de valeur" },
  { id: "drop",     label: "Pas urgent, pas important", short: "À éliminer ou plus tard", color: "#8B92A3", emoji: "🗑️", desc: "Distractions, faible ROI" },
];

// ═══ ÉQUIPE ═══
export const TEAM = [
  { id: "basile", name: "Basile", color: "#0F1B2D", initials: "B" },
  { id: "greg",   name: "Greg",   color: "#1F6B4A", initials: "G" },
  { id: "hippo",  name: "Hippo",  color: "#D4A95C", initials: "H" },
  { id: "aurore", name: "Aurore", color: "#A82E2E", initials: "A" },
  { id: "unassigned", name: "Non assigné", color: "#8B92A3", initials: "?" },
];

export const PHASES = [
  { id: "p0",  label: "Phase 0 — Validation & Recherches",   short: "P0 Validation",  period: "Mois 0-1",  color: "#A855F7" },
  { id: "p1",  label: "Phase 1 — Légal & Structuration",     short: "P1 Légal",       period: "Mois 1-2",  color: "#3B82F6" },
  { id: "p2",  label: "Phase 2 — Design & UX",               short: "P2 Design",      period: "Mois 2-3",  color: "#EC4899" },
  { id: "p3",  label: "Phase 3 — Infra & Architecture",      short: "P3 Infra",       period: "Mois 2-3",  color: "#06B6D4" },
  { id: "p4",  label: "Phase 4 — Dev MVP Backend",           short: "P4 Backend",     period: "Mois 3-5",  color: "#10B981" },
  { id: "p5",  label: "Phase 5 — Dev MVP Frontend",          short: "P5 Frontend",    period: "Mois 3-5",  color: "#84CC16" },
  { id: "p6",  label: "Phase 6 — Sécurité & Qualité",        short: "P6 Sécurité",    period: "Mois 4-5",  color: "#F59E0B" },
  { id: "p7",  label: "Phase 7 — Pré-lancement & Marketing", short: "P7 Marketing",   period: "Mois 4-5",  color: "#F97316" },
  { id: "p8",  label: "Phase 8 — Lancement",                 short: "P8 Lancement",   period: "Mois 5-6",  color: "#EF4444" },
  { id: "p9",  label: "Phase 9 — V1 Automatisation",         short: "P9 V1",          period: "Mois 5-8",  color: "#D4A95C" },
  { id: "p10", label: "Phase 10 — Scale & Série A",          short: "P10 Scale",      period: "Mois 8-12", color: "#A855F7" },
  { id: "p11", label: "Phase 11 — International & V3",       short: "P11 Intl",       period: "Mois 12+",  color: "#3B82F6" },
];

// ═══════════════════════════════════════════════════════════════
// 159 TICKETS — chacun avec quadrant Eisenhower + assignee
// ═══════════════════════════════════════════════════════════════
export const DEFAULT_TICKETS = [
  // === P0 — VALIDATION ===
  { id: "T001", phase: "p0", title: "Définir l'ICP précis et 3 personas détaillés", desc: "Profil démographique, psychographique, comportemental. Inclure : âge, revenu, profession, douleurs, motivations, freins, canaux de découverte. Créer 3 personas distincts (ex: salarié 30 ans, freelance 35 ans, jeune cadre 26 ans).", fib: 3, status: "todo", deps: "", quadrant: "do",       assignee: "basile" },
  { id: "T002", phase: "p0", title: "Mener 15 entretiens utilisateurs ciblés", desc: "Recruter via LinkedIn, Reddit, réseau perso. Script Mom Test : 'Parle-moi de la dernière fois où tu as eu un problème d'argent', 'Comment tu gères tes abonnements ?'. Enregistrer + transcrire. Identifier patterns récurrents.", fib: 5, status: "todo", deps: "T001", quadrant: "do",   assignee: "basile" },
  { id: "T003", phase: "p0", title: "Sondage en ligne 200+ répondants", desc: "Typeform/Tally. 15 questions max : douleurs financières, WTP, apps utilisées, freins. Diffuser sur Reddit (r/vosfinances), Twitter, Facebook groups. Budget pub Meta 100€ pour booster.", fib: 5, status: "todo", deps: "T001", quadrant: "schedule", assignee: "aurore" },
  { id: "T004", phase: "p0", title: "Analyse approfondie Bankin' (concurrent #1)", desc: "Télécharger l'app, créer un compte, tester toutes les fonctionnalités. Documenter : tarifs, onboarding, UX, modules, points faibles. Lire 100+ avis App Store/Play Store. Identifier les frustrations récurrentes.", fib: 5, status: "todo", deps: "", quadrant: "do",        assignee: "hippo" },
  { id: "T005", phase: "p0", title: "Analyse approfondie Lydia/Sumeria", desc: "Test complet, mapping features, lecture reviews. Focus sur leur stratégie de monétisation et leur conflit d'intérêts en tant que néobanque vs Alfred neutre.", fib: 5, status: "todo", deps: "", quadrant: "schedule",                               assignee: "hippo" },
  { id: "T006", phase: "p0", title: "Analyse approfondie Linxo + Cleo + Origin", desc: "Trois apps PFM avec touches d'IA. Tester Linxo (FR), Cleo (UK avec tone fun), Origin (US wealth). Identifier ce qui manque chez chacun et pourquoi ils ne convertissent pas.", fib: 5, status: "todo", deps: "", quadrant: "schedule",      assignee: "hippo" },
  { id: "T007", phase: "p0", title: "Étude de cas Rocket Money (modèle US à dupliquer)", desc: "Étudier en détail leur modèle 'négociation as a service', leurs partenariats, leur pricing (3-12$/mois + 40% économie mois 1). Comprendre pourquoi ils ne viennent pas en EU. Lire toutes leurs interviews fondateurs.", fib: 3, status: "todo", deps: "", quadrant: "schedule", assignee: "aurore" },
  { id: "T008", phase: "p0", title: "Analyse concurrents indirects (Selectra, Papernest, AirHelp)", desc: "Comparateurs et services de récupération. Comprendre leurs commissions, leurs partenariats, leurs taux de conversion. Sources d'opportunités de partenariats pour Alfred.", fib: 3, status: "todo", deps: "", quadrant: "schedule",  assignee: "hippo" },
  { id: "T009", phase: "p0", title: "Veille Reddit r/vosfinances + r/JeuneActif", desc: "Lire les 200 derniers posts populaires. Documenter douleurs récurrentes : abos, banques, fiscalité, énergie, vols, négociation. Créer un fichier de citations utilisables en marketing.", fib: 2, status: "todo", deps: "", quadrant: "delegate",          assignee: "aurore" },
  { id: "T010", phase: "p0", title: "Veille TikTok/Instagram sur la finance perso FR", desc: "Identifier les hooks qui marchent, les créateurs influents, les formats viraux. Cartographier les comptes 50k-500k followers en finance perso pour partenariats futurs.", fib: 2, status: "todo", deps: "", quadrant: "delegate",                  assignee: "aurore" },
  { id: "T011", phase: "p0", title: "Calcul TAM/SAM/SOM affiné avec sources", desc: "Croiser sources : Statista, IBISWorld, Grand View Research, Banque de France. Méthodologie top-down + bottom-up. Justifier chaque hypothèse. Document partagé pour pitch deck VC.", fib: 3, status: "todo", deps: "", quadrant: "schedule",            assignee: "basile" },
  { id: "T012", phase: "p0", title: "Définir la VRAIE proposition de valeur (PVU)", desc: "Pas une description marketing — une équation : 'Pour [ICP] qui [douleur], Alfred est [catégorie] qui [bénéfice unique], contrairement à [alternative]'. Itérer 10 versions. Tester en interviews.", fib: 5, status: "todo", deps: "T001,T002", quadrant: "do", assignee: "basile" },
  { id: "T013", phase: "p0", title: "Identifier 3 différenciateurs durables (moats)", desc: "Pas des features — des barrières à l'entrée : données accumulées, partenariats exclusifs, neutralité structurelle, compliance avancée. Documenter pourquoi un concurrent ne peut pas copier en 6 mois.", fib: 3, status: "todo", deps: "T012", quadrant: "do",  assignee: "basile" },
  { id: "T014", phase: "p0", title: "Test A/B 3 messages publicitaires sur landing fictive", desc: "3 variantes de landing simple (Webflow). 100€ Meta Ads vers chaque. Mesurer CTR + taux d'inscription waitlist. Le gagnant définit le messaging principal.", fib: 5, status: "todo", deps: "T012", quadrant: "schedule",                       assignee: "greg" },
  { id: "T015", phase: "p0", title: "Mesure WTP via 50 mini-interviews", desc: "Question-clé : 'Si je te garantissais 600€ d'économies par an, combien serais-tu prêt à payer par mois ?'. Distribution des réponses → pricing optimal entre 4,99 et 14,99€.", fib: 5, status: "todo", deps: "T002", quadrant: "do",                       assignee: "basile" },
  { id: "T016", phase: "p0", title: "Validation problem-solution fit (go/no-go)", desc: "Critère : 70%+ des interviewés disent 'oui je paierais pour ça'. Si non → pivoter le concept ou l'ICP. Décision écrite avant phase 1.", fib: 3, status: "todo", deps: "T002,T015", quadrant: "do",                                                  assignee: "basile" },
  { id: "T017", phase: "p0", title: "Élevator pitch + tagline finalisés", desc: "30 secondes max. Doit faire comprendre : qui (ICP), quoi (Alfred fait X), pourquoi unique (vs Y), preuve (économie moyenne). Tester sur 10 personnes hors cible.", fib: 1, status: "todo", deps: "T012", quadrant: "do",                                       assignee: "basile" },

  // === P1 — LÉGAL ===
  { id: "T018", phase: "p1", title: "Recherche INPI : disponibilité 'Alfred' (classes 9, 36, 42)", desc: "Vérifier sur la base INPI que 'Alfred' n'est pas déposé en classe 9 (apps), 36 (services financiers), 42 (services techno). Si conflit → trouver alternative. Coût : 0€.", fib: 1, status: "todo", deps: "", quadrant: "do",                       assignee: "basile" },
  { id: "T019", phase: "p1", title: "Réservation domaines (.com, .fr, .app, .io)", desc: "Acheter sur OVH ou Gandi. Budget ~100-300€ selon disponibilité. Si .com pas dispo, alternatives : alfred.fr, alfred.app, getalfred.com, alfred-app.com.", fib: 1, status: "todo", deps: "T018", quadrant: "do",                                          assignee: "basile" },
  { id: "T020", phase: "p1", title: "Réservation handles sociaux", desc: "Instagram, TikTok, Twitter/X, LinkedIn, YouTube, Facebook. Tous en @alfred ou @alfredapp ou @getalfred. Cohérence absolue. Faire vite avant qu'un autre les prenne.", fib: 1, status: "todo", deps: "T018", quadrant: "do",                                                  assignee: "aurore" },
  { id: "T021", phase: "p1", title: "Choix structure juridique : SAS vs SASU", desc: "SAS si 2+ associés, SASU si solo. Consulter expert-comptable (1h gratuite). Avantages SAS : flexibilité, image pro, levée de fonds facile. Coût création ~500-1500€.", fib: 2, status: "todo", deps: "", quadrant: "do",                                       assignee: "basile" },
  { id: "T022", phase: "p1", title: "Création de l'entité légale + statuts", desc: "Via LegalStart, Captain Contrat ou notaire. Capital minimum 1€ (recommandé 1000-10000€). Définir parts sociales, dirigeants, siège social. Délai 2-3 semaines.", fib: 3, status: "todo", deps: "T021", quadrant: "do",                                       assignee: "basile" },
  { id: "T023", phase: "p1", title: "Ouverture compte bancaire pro", desc: "Qonto ou Shine pour rapidité (24-48h). Frais ~9-20€/mois. Lié au K-bis de la société. Nécessaire pour tous les contrats fournisseurs et facturation.", fib: 1, status: "todo", deps: "T022", quadrant: "do",                                                                  assignee: "basile" },
  { id: "T024", phase: "p1", title: "Dépôt INPI : marque + logo", desc: "Une fois logo finalisé. ~250€ pour 1 classe, +42€ par classe additionnelle. Couvrir classes 9, 36, 42. Protection 10 ans renouvelable.", fib: 3, status: "todo", deps: "T018", quadrant: "schedule",                                                                            assignee: "basile" },
  { id: "T025", phase: "p1", title: "Étude juridique : licence AISP propre vs partenariat agrégateur", desc: "Décision stratégique majeure. AISP propre = 50-150k€ + 6 mois. Partenariat (Powens/Bridge) = délégation, plus rapide, moins coûteux. Recommandation MVP : partenariat. Documenter pour pitch VC.", fib: 5, status: "todo", deps: "", quadrant: "do", assignee: "greg" },
  { id: "T026", phase: "p1", title: "Demo + tarification Powens", desc: "Contacter sales Powens (ex-Budget Insight). Demander : pricing par user, par appel API, SLA, support, qualité matching merchants, banques couvertes. Demander accès sandbox.", fib: 2, status: "todo", deps: "", quadrant: "do",                                                  assignee: "greg" },
  { id: "T027", phase: "p1", title: "Demo + tarification Bridge by Bankin'", desc: "Contacter sales Bridge. Mêmes critères. Avantage Bridge : qualité matching réputée meilleure. Inconvénient : owned by Bankin' = concurrent indirect. À évaluer.", fib: 2, status: "todo", deps: "", quadrant: "do",                                              assignee: "greg" },
  { id: "T028", phase: "p1", title: "Demo + tarification Tink (Visa)", desc: "Pour couverture EU élargie (V2/V3). Plus cher mais coverage paneuropéen. Utile si lancement BE/LU/DE prévu rapidement.", fib: 2, status: "todo", deps: "", quadrant: "schedule",                                                                                          assignee: "greg" },
  { id: "T029", phase: "p1", title: "Choix final agrégateur DSP2", desc: "Décision basée sur : pricing au volume, qualité matching, banques FR couvertes (>95%), API moderne, support technique, SLA >99.5%. Documenter le scoring.", fib: 1, status: "todo", deps: "T026,T027,T028", quadrant: "do",                                                  assignee: "greg" },
  { id: "T030", phase: "p1", title: "Négociation et signature contrat agrégateur", desc: "Cycle 2-4 semaines. Points clés : volumes minimums, prix dégressifs, clauses d'exclusivité (à éviter), SLA, RGPD compliance, transferts de données, durée d'engagement.", fib: 5, status: "todo", deps: "T029", quadrant: "do",                       assignee: "basile" },
  { id: "T031", phase: "p1", title: "Rédaction CGU avec avocat fintech", desc: "Avocat spécialisé (Dechert, August Debouzy, ou cabinet boutique). Budget 3-6k€. Couvrir : nature du service (information, pas de conseil financier), responsabilité, traitement erreurs IA, résiliation.", fib: 8, status: "todo", deps: "", quadrant: "schedule", assignee: "basile" },
  { id: "T032", phase: "p1", title: "Politique de confidentialité RGPD complète", desc: "Avec l'avocat. Documenter : données collectées, finalités, durée de conservation, sous-traitants (Powens, AWS, Stripe), droits utilisateurs, transferts hors UE.", fib: 5, status: "todo", deps: "T031", quadrant: "schedule",                       assignee: "basile" },
  { id: "T033", phase: "p1", title: "Désignation DPO (interne ou externe)", desc: "Obligatoire si traitement à grande échelle de données financières. DPO externe ~3-8k€/an chez Privacy Tech, Lexing, Dastra. Plus simple en early-stage qu'un DPO salarié.", fib: 3, status: "todo", deps: "T032", quadrant: "schedule",                       assignee: "basile" },
  { id: "T034", phase: "p1", title: "Mise en place registre RGPD (Article 30)", desc: "Document obligatoire. Lister tous les traitements de données, finalités, catégories de personnes, durées, sous-traitants. Outil : Dastra, OneTrust ou Notion structuré.", fib: 3, status: "todo", deps: "T033", quadrant: "schedule",                   assignee: "basile" },
  { id: "T035", phase: "p1", title: "Préparation dossier conformité AI Act", desc: "AI Act EU entré en vigueur en 2024-2026. Alfred = 'limited risk AI'. Obligations : transparence, explicabilité des décisions automatisées, droit de contester. Préparer documentation technique.", fib: 5, status: "todo", deps: "T032", quadrant: "schedule",  assignee: "greg" },
  { id: "T036", phase: "p1", title: "Souscription cyber-assurance", desc: "Couvre : data breach, RC pro, atteinte à l'image, frais de notification CNIL. ~2-5k€/an pour démarrage. Hiscox, AIG, Stoïk (spécialiste tech). Indispensable dès qu'on traite des données financières.", fib: 3, status: "todo", deps: "T022", quadrant: "schedule",     assignee: "basile" },
  { id: "T037", phase: "p1", title: "Mentions légales + Conditions de vente complètes", desc: "Sur la landing et l'app. Inclure : éditeur, hébergeur, médiateur de la consommation, droit de rétractation, conditions de remboursement (garantie 90j).", fib: 2, status: "todo", deps: "T031", quadrant: "schedule",                                  assignee: "basile" },

  // === P2 — DESIGN ===
  { id: "T038", phase: "p2", title: "Création du logo Alfred (designer ou Fiverr)", desc: "Brief : élégant, classe, encre/champagne, nœud papillon (charte Alfred). Budget : 200-2000€ selon designer. 3 variantes minimum, livrables vectoriels (SVG, PDF, AI).", fib: 3, status: "done", deps: "", quadrant: "do",                              assignee: "hippo" },
  { id: "T039", phase: "p2", title: "Brand book Alfred complet", desc: "Document Figma 20-30 pages : logo + variantes, palette couleurs (encre #0F1B2D, champagne #D4A95C, ivoire #F7F3EB, émeraude #1F6B4A), typographie, iconographie, ton de voix.", fib: 5, status: "doing", deps: "T038", quadrant: "do",                                       assignee: "hippo" },
  { id: "T040", phase: "p2", title: "User personas détaillés (3 minimum)", desc: "Format Figma ou Notion. Chaque persona : photo, citation, démographique, contexte, douleurs, objectifs, freins, déclencheurs d'achat, canaux préférés. Basé sur les entretiens utilisateurs réels.", fib: 5, status: "todo", deps: "T002", quadrant: "do",          assignee: "hippo" },
  { id: "T041", phase: "p2", title: "User journey mapping de bout en bout", desc: "Du premier contact (TikTok/SEO) → onboarding → première économie → fidélisation → recommandation. Identifier touchpoints, émotions, frictions à chaque étape.", fib: 5, status: "todo", deps: "T040", quadrant: "schedule",                                  assignee: "hippo" },
  { id: "T042", phase: "p2", title: "Wireframes basse fidélité (Whimsical)", desc: "Tous les écrans de l'app en simple wireframe. Pas de design final. Objectif : valider la structure et la navigation. Couvrir 100% du parcours MVP.", fib: 5, status: "todo", deps: "T041", quadrant: "schedule",                                              assignee: "hippo" },
  { id: "T043", phase: "p2", title: "Maquettes haute fidélité — Onboarding", desc: "Figma. 8-12 écrans : welcome, explication valeur, demande permissions, connexion bancaire DSP2, premier scan, premier insight. Animations clés. Mode clair + sombre.", fib: 8, status: "todo", deps: "T039,T042", quadrant: "do",                              assignee: "hippo" },
  { id: "T044", phase: "p2", title: "Maquettes haute fidélité — Dashboard principal", desc: "Vue d'ensemble : économies du mois, alertes en attente, actions récentes, modules actifs. Design system rigoureux, cohérent avec le brand.", fib: 8, status: "todo", deps: "T039,T042", quadrant: "do",                                                assignee: "hippo" },
  { id: "T045", phase: "p2", title: "Maquettes module factures à venir", desc: "Liste des factures détectées, alertes 5j avant, action 'Mettre de côté' en un tap, historique.", fib: 5, status: "todo", deps: "T044", quadrant: "schedule",                                                                                                            assignee: "hippo" },
  { id: "T046", phase: "p2", title: "Maquettes module abonnements morts", desc: "Liste avec score d'utilisation, propositions de résiliation, lettres préremplies, suivi des résiliations en cours.", fib: 5, status: "todo", deps: "T044", quadrant: "schedule",                                                                                       assignee: "hippo" },
  { id: "T047", phase: "p2", title: "Design system Alfred (composants Figma)", desc: "Bibliothèque de composants réutilisables : boutons, inputs, cards, modals, alerts, navigation, charts. Naming convention rigoureuse. Auto-layout systématique.", fib: 8, status: "todo", deps: "T039", quadrant: "schedule",                                  assignee: "hippo" },
  { id: "T048", phase: "p2", title: "Prototype interactif Figma (clickable)", desc: "Tous les écrans liés avec interactions. Doit pouvoir simuler le parcours complet 'install → première économie' sans coder.", fib: 5, status: "todo", deps: "T043,T044,T045,T046", quadrant: "schedule",                                                          assignee: "hippo" },
  { id: "T049", phase: "p2", title: "Tests utilisateurs sur prototype (10 personnes)", desc: "Sessions 30 min via Maze ou Lookback. Identifier frictions, malentendus, abandons. Itérer 2 fois avant de coder. Chaque test évite 50h de dev.", fib: 5, status: "todo", deps: "T048", quadrant: "do",                                                  assignee: "aurore" },
  { id: "T050", phase: "p2", title: "Itération design selon feedback tests", desc: "Documenter chaque itération avec versions. Critère go/no-go : 80%+ des testeurs comprennent la valeur en <60s.", fib: 5, status: "todo", deps: "T049", quadrant: "schedule",                                                                                       assignee: "hippo" },

  // === P3 — INFRA ===
  { id: "T051", phase: "p3", title: "Choix stack backend (Node.js vs Python FastAPI)", desc: "Critères : écosystème IA (Python > Node), perf (équivalent), recrutement (Node plus large), expérience équipe. Recommandation : Python FastAPI si IA-heavy, Node si team JS.", fib: 3, status: "todo", deps: "", quadrant: "do",                       assignee: "greg" },
  { id: "T052", phase: "p3", title: "Choix stack frontend mobile (React Native vs Flutter)", desc: "RN : écosystème JS, recrutement facile. Flutter : perf supérieures, plus jeune. Pour Alfred (UX mobile + recrutement) : RN + Expo recommandé.", fib: 3, status: "todo", deps: "", quadrant: "do",                                                  assignee: "greg" },
  { id: "T053", phase: "p3", title: "Choix cloud provider (AWS eu-west vs OVH vs Scaleway)", desc: "AWS = leader, écosystème, eu-west-1 RGPD compliant. OVH/Scaleway = souveraineté FR, moins cher. Trade-off à arbitrer. Coût MVP : 200-500€/mois.", fib: 3, status: "todo", deps: "", quadrant: "do",                                              assignee: "greg" },
  { id: "T054", phase: "p3", title: "Architecture système globale (diagram + ADR)", desc: "Schéma archi : mobile → API gateway → microservices → DB. Documenter chaque décision en ADR. Minimum 5 ADR : monolithe vs micro, BDD, queue, cache, secrets.", fib: 8, status: "todo", deps: "T051,T053", quadrant: "do",                              assignee: "greg" },
  { id: "T055", phase: "p3", title: "Schéma base de données PostgreSQL", desc: "Tables : users, accounts, transactions, subscriptions, alerts, actions, savings_history, payments. Contraintes, index, relations, triggers. Considérer le sharding futur.", fib: 5, status: "todo", deps: "T054", quadrant: "do",                                  assignee: "greg" },
  { id: "T056", phase: "p3", title: "Spécifications API (OpenAPI/Swagger)", desc: "Documenter tous les endpoints : auth, users, accounts, transactions, actions. Versionning v1. Réponses standardisées. Codes d'erreur. À utiliser pour générer les SDK mobile.", fib: 5, status: "todo", deps: "T054", quadrant: "schedule",                  assignee: "greg" },
  { id: "T057", phase: "p3", title: "Setup repo GitHub (mono ou multi)", desc: "Mono-repo avec Turborepo recommandé pour solo/petite équipe. Branches : main (prod), staging, develop. Branch protection rules.", fib: 1, status: "todo", deps: "", quadrant: "do",                                                                                          assignee: "greg" },
  { id: "T058", phase: "p3", title: "Setup CI/CD GitHub Actions", desc: "Pipelines : tests automatiques sur PR, lint, type-check, build, déploiement automatique sur staging, déploiement manuel sur prod. Secrets via GitHub.", fib: 3, status: "todo", deps: "T057", quadrant: "schedule",                                                            assignee: "greg" },
  { id: "T059", phase: "p3", title: "Setup environnements (dev, staging, prod)", desc: "3 envs distincts sur AWS. Variables d'env via Doppler ou AWS Secrets Manager. Bases de données isolées. URLs distinctes.", fib: 5, status: "todo", deps: "T053", quadrant: "schedule",                                                                          assignee: "greg" },
  { id: "T060", phase: "p3", title: "Setup monitoring (Sentry + Datadog/Grafana)", desc: "Sentry pour les erreurs (front + back), Datadog ou Grafana Cloud pour metrics + logs. Alertes Slack en cas d'incident.", fib: 3, status: "todo", deps: "T059", quadrant: "schedule",                                                                       assignee: "greg" },
  { id: "T061", phase: "p3", title: "Setup analytics produit (Mixpanel ou PostHog)", desc: "PostHog cloud recommandé : open source, pricing fair, RGPD compliant en EU. Setup events tracking dès J1 du dev. Dashboards de cohortes.", fib: 2, status: "todo", deps: "", quadrant: "schedule",                                                          assignee: "greg" },
  { id: "T062", phase: "p3", title: "Configuration DNS et certificats SSL", desc: "Cloudflare ou Route53 pour DNS. Let's Encrypt via AWS Certificate Manager. Wildcard pour sous-domaines (api.alfred.app, admin.alfred.app).", fib: 2, status: "todo", deps: "T019", quadrant: "schedule",                                                          assignee: "greg" },

  // === P4 — BACKEND ===
  { id: "T063", phase: "p4", title: "Backend : API Gateway + middleware globaux", desc: "Setup FastAPI/Express. Middleware : auth, rate limiting, CORS, request logging, error handling. Health check endpoint. Versionning /v1.", fib: 5, status: "todo", deps: "T056", quadrant: "do",                                                                  assignee: "greg" },
  { id: "T064", phase: "p4", title: "Backend : Service authentification (JWT + refresh)", desc: "Sign up, sign in, refresh token, password reset, magic link. Hash bcrypt. JWT 15 min + refresh 30j. Email vérification obligatoire.", fib: 8, status: "todo", deps: "T063", quadrant: "do",                                                          assignee: "greg" },
  { id: "T065", phase: "p4", title: "Backend : Intégration agrégateur DSP2 (Powens/Bridge)", desc: "Onboarding flow : SDK / WebView pour connexion bancaire, callback de validation, stockage tokens chiffrés, refresh consent tous les 90j (DSP2). Gestion erreurs.", fib: 13, status: "todo", deps: "T030,T063", quadrant: "do",                  assignee: "greg" },
  { id: "T066", phase: "p4", title: "Backend : Service utilisateurs + profils", desc: "CRUD user, gestion préférences, paramètres notifications, consentements RGPD, suppression compte (droit à l'oubli).", fib: 5, status: "todo", deps: "T064", quadrant: "schedule",                                                                                  assignee: "greg" },
  { id: "T067", phase: "p4", title: "Backend : Service transactions (parsing + normalisation)", desc: "Récupération via agrégateur, normalisation merchants (Spotify vs SPOTIFY*123), classification automatique, détection récurrences, enrichissement (logos, types).", fib: 8, status: "todo", deps: "T065", quadrant: "do",                  assignee: "greg" },
  { id: "T068", phase: "p4", title: "Backend : Service détection abonnements (algo ML)", desc: "Algorithme de détection de récurrence : montants similaires, intervalles réguliers, mêmes merchants. ML classifier pour 'abonnement vs paiement ponctuel'. Dataset training : 10k transactions labellisées.", fib: 13, status: "todo", deps: "T067", quadrant: "do", assignee: "greg" },
  { id: "T069", phase: "p4", title: "Backend : Service détection factures à venir", desc: "Prédiction : sur la base des récurrences passées, prévoir factures EDF, internet, etc. Alerter 5 jours avant. Adaptable selon le pattern utilisateur.", fib: 8, status: "todo", deps: "T067", quadrant: "do",                                          assignee: "greg" },
  { id: "T070", phase: "p4", title: "Backend : Service notifications (Firebase FCM + emails)", desc: "Push notifications mobile (Firebase), emails transactionnels (Resend ou SendGrid). Templates customisés. Préférences user respectées.", fib: 5, status: "todo", deps: "T066", quadrant: "schedule",                                          assignee: "greg" },
  { id: "T071", phase: "p4", title: "Backend : Intégration Stripe (abonnements)", desc: "Stripe Subscriptions API. Plans Free/Alfred+/Pro. Webhooks pour gérer renouvellements, échecs de paiement, annulations. Période d'essai 14j.", fib: 5, status: "todo", deps: "T064", quadrant: "do",                                                          assignee: "greg" },
  { id: "T072", phase: "p4", title: "Backend : Service consentements DSP2 (re-auth 90j)", desc: "Détection des consentements qui expirent dans 7-14j, notification user, flow de renouvellement, fallback si expiré (mode dégradé).", fib: 8, status: "todo", deps: "T065", quadrant: "schedule",                                                  assignee: "greg" },
  { id: "T073", phase: "p4", title: "Backend : API publique pour app mobile", desc: "Endpoints REST pour tous les besoins mobile. Réponses optimisées (pagination, filtrage, projection). GraphQL en option pour V2.", fib: 5, status: "todo", deps: "T067,T068,T069", quadrant: "schedule",                                                          assignee: "greg" },
  { id: "T074", phase: "p4", title: "Backend : Webhook handlers (Powens, Stripe)", desc: "Endpoints pour recevoir events agrégateur (nouvelles transactions) et Stripe (paiements). Validation signatures. Idempotence. Retry automatique.", fib: 5, status: "todo", deps: "T065,T071", quadrant: "schedule",                                       assignee: "greg" },
  { id: "T075", phase: "p4", title: "Backend : Tests unitaires (couverture > 70%)", desc: "Pytest ou Jest. Mocks pour services externes. CI bloque les PR avec coverage en baisse. Focus sur la logique métier critique.", fib: 8, status: "todo", deps: "T063", quadrant: "schedule",                                                                  assignee: "greg" },
  { id: "T076", phase: "p4", title: "Backend : Documentation API (Swagger UI)", desc: "Documentation auto-générée via OpenAPI. Hébergée sur api.alfred.app/docs. Examples de requests/responses. Versionning visible.", fib: 3, status: "todo", deps: "T056,T073", quadrant: "delegate",                                                                  assignee: "greg" },

  // === P5 — FRONTEND ===
  { id: "T077", phase: "p5", title: "Setup React Native + Expo", desc: "Init projet avec Expo. Config TypeScript. Linting (ESLint), formatting (Prettier). Config build iOS + Android. Test sur simulateurs.", fib: 2, status: "todo", deps: "T052", quadrant: "do",                                                                                            assignee: "greg" },
  { id: "T078", phase: "p5", title: "Frontend : Système de navigation (React Navigation)", desc: "Stack + Tab navigation. Routes typées. Deep linking (alfred://). Gestion auth state (logged in vs out).", fib: 5, status: "todo", deps: "T077", quadrant: "do",                                                                                          assignee: "greg" },
  { id: "T079", phase: "p5", title: "Frontend : Composants design system (Storybook)", desc: "Implémenter tous les composants du design system Figma. Storybook pour les visualiser. Tests visuels. ~30-50 composants.", fib: 8, status: "todo", deps: "T047,T077", quadrant: "schedule",                                                            assignee: "greg" },
  { id: "T080", phase: "p5", title: "Frontend : Écrans d'onboarding", desc: "5-8 écrans : welcome, valeur prop, permissions, connexion bancaire, premier scan, configuration alertes. Animations Reanimated. Skip possible.", fib: 5, status: "todo", deps: "T043,T079", quadrant: "do",                                                              assignee: "greg" },
  { id: "T081", phase: "p5", title: "Frontend : Écran connexion bancaire DSP2", desc: "WebView pour SDK Powens/Bridge. Loader pendant scan. Gestion erreurs (banque indispo, user refuse). Confirmation succès.", fib: 8, status: "todo", deps: "T065,T080", quadrant: "do",                                                                          assignee: "greg" },
  { id: "T082", phase: "p5", title: "Frontend : Dashboard principal", desc: "Vue d'ensemble : économies cumulées, alertes en cours, actions à valider, modules actifs. Pull-to-refresh. Charts économies (Victory ou Recharts).", fib: 8, status: "todo", deps: "T044,T079", quadrant: "do",                                                          assignee: "greg" },
  { id: "T083", phase: "p5", title: "Frontend : Module factures à venir", desc: "Liste avec dates, montants, action 'mettre de côté'. Filtre par type. Historique des factures passées.", fib: 5, status: "todo", deps: "T045,T082", quadrant: "schedule",                                                                                                  assignee: "greg" },
  { id: "T084", phase: "p5", title: "Frontend : Module abonnements morts", desc: "Liste avec score d'utilisation, dernière utilisation, montant cumulé perdu, action 'résilier'. Confirmation avant action.", fib: 5, status: "todo", deps: "T046,T082", quadrant: "schedule",                                                                          assignee: "greg" },
  { id: "T085", phase: "p5", title: "Frontend : Module prélèvements suspects", desc: "Liste des transactions inconnues. Action 'reconnaître' (false positive) ou 'contester' (génère lettre). Historique des contestations.", fib: 5, status: "todo", deps: "T082", quadrant: "schedule",                                                            assignee: "greg" },
  { id: "T086", phase: "p5", title: "Frontend : Notifications push (config)", desc: "Setup Firebase. Demande permission au bon moment (pas à l'install). Préférences granulaires. Deep linking depuis notif.", fib: 3, status: "todo", deps: "T070,T077", quadrant: "schedule",                                                                       assignee: "greg" },
  { id: "T087", phase: "p5", title: "Frontend : Système de validation tap (1 tap action)", desc: "Composant réutilisable : 'Voici ce qu'Alfred propose, je lance ?'. Animation loading. Feedback succès. Undo possible 30s.", fib: 3, status: "todo", deps: "T079", quadrant: "do",                                                                  assignee: "greg" },
  { id: "T088", phase: "p5", title: "Frontend : Écran historique des actions", desc: "Timeline des actions Alfred : résiliations, alertes, contestations. Statut de chaque action. Économie réalisée cumulée.", fib: 3, status: "todo", deps: "T082", quadrant: "schedule",                                                                            assignee: "greg" },
  { id: "T089", phase: "p5", title: "Frontend : Écran paramètres utilisateur", desc: "Profil, préférences notifications, consentements RGPD, abonnement, comptes bancaires connectés (déconnecter), suppression compte.", fib: 3, status: "todo", deps: "T066", quadrant: "schedule",                                                                  assignee: "greg" },
  { id: "T090", phase: "p5", title: "Frontend : Écran abonnement Stripe (in-app)", desc: "Comparatif Free/Alfred+/Pro. CTA upgrade. Stripe Payment Sheet (RN SDK). Confirmation. Gestion downgrade/cancel.", fib: 5, status: "todo", deps: "T071,T079", quadrant: "do",                                                                              assignee: "greg" },
  { id: "T091", phase: "p5", title: "Frontend : Tests E2E (Detox ou Maestro)", desc: "Maestro recommandé : plus simple, YAML. Couvrir les 5 parcours critiques : signup, connexion bancaire, validation action, upgrade payment, suppression compte.", fib: 8, status: "todo", deps: "T080,T081,T082,T087,T090", quadrant: "schedule",              assignee: "greg" },
  { id: "T092", phase: "p5", title: "Frontend : Optimisation performances", desc: "Bundle size, lazy loading, image optimization, animations 60fps, démarrage app < 2s. Profiling avec Flipper.", fib: 5, status: "todo", deps: "T091", quadrant: "delegate",                                                                                              assignee: "greg" },

  // === P6 — SÉCURITÉ ===
  { id: "T093", phase: "p6", title: "Audit sécurité OWASP (interne)", desc: "Checklist OWASP Top 10. Test injection SQL, XSS, CSRF, broken auth, sensitive data exposure. Outils : OWASP ZAP, Burp Suite Community.", fib: 8, status: "todo", deps: "T063,T080", quadrant: "do",                                                                          assignee: "greg" },
  { id: "T094", phase: "p6", title: "Pentests externes (prestataire spécialisé)", desc: "Mandater un cabinet (Synacktiv, Wavestone, Almond). Coût 5-15k€. Test boîte noire + grise. Rapport d'audit obligatoire pour pitch VC.", fib: 8, status: "todo", deps: "T093", quadrant: "do",                                                                  assignee: "basile" },
  { id: "T095", phase: "p6", title: "Chiffrement AES-256 des données sensibles", desc: "Toutes les données financières en BDD chiffrées at-rest. Tokens bancaires dans AWS KMS. Clés rotation automatique 90j.", fib: 5, status: "todo", deps: "T055", quadrant: "do",                                                                              assignee: "greg" },
  { id: "T096", phase: "p6", title: "TLS 1.3 partout + HSTS", desc: "API en HTTPS only. HSTS preload. Certificats validés. Test SSLLabs Grade A+. Préparer la transition vers TLS 1.4 quand dispo.", fib: 2, status: "todo", deps: "T062", quadrant: "schedule",                                                                                            assignee: "greg" },
  { id: "T097", phase: "p6", title: "Rate limiting + anti-abuse", desc: "Limites par IP, par user, par endpoint. Cloudflare ou rate limiter custom. Anti-scraping. Détection de comportements anormaux.", fib: 3, status: "todo", deps: "T063", quadrant: "schedule",                                                                                      assignee: "greg" },
  { id: "T098", phase: "p6", title: "Plan de continuité d'activité (PCA)", desc: "Que se passe-t-il si AWS eu-west-1 down ? Si Powens down ? Documenter procédures, responsables, communications. Test annuel.", fib: 3, status: "todo", deps: "", quadrant: "schedule",                                                                                  assignee: "basile" },
  { id: "T099", phase: "p6", title: "Procédure incident RGPD (notification CNIL 72h)", desc: "Workflow documenté : détection breach, évaluation, notification CNIL, notification users. Templates prêts. Responsable identifié.", fib: 3, status: "todo", deps: "T033", quadrant: "schedule",                                                       assignee: "basile" },
  { id: "T100", phase: "p6", title: "Backup automatique BDD (daily + retention 30j)", desc: "Snapshots PostgreSQL automatiques. Backups crossregion. Test de restoration mensuel. Documenter le RTO/RPO.", fib: 3, status: "todo", deps: "T055", quadrant: "schedule",                                                                                  assignee: "greg" },

  // === P7 — PRÉ-LANCEMENT ===
  { id: "T101", phase: "p7", title: "Création landing page Webflow", desc: "Headline + sub, valeur prop, démo (GIF ou vidéo), social proof, FAQ, CTA waitlist. Mobile-first. Performance Lighthouse > 90.", fib: 5, status: "todo", deps: "T012,T038", quadrant: "do",                                                                                  assignee: "aurore" },
  { id: "T102", phase: "p7", title: "Système liste d'attente (Tally + Mailchimp)", desc: "Form Tally simple : email + 2 questions de qualification. Auto-add Mailchimp. Welcome email avec promesse de l'invitation bêta.", fib: 2, status: "todo", deps: "T101", quadrant: "do",                                                                  assignee: "aurore" },
  { id: "T103", phase: "p7", title: "Setup comptes sociaux (TikTok, Instagram, X, LinkedIn)", desc: "Bio cohérente, avatar = logo, lien vers landing. Suivre 50 comptes pertinents par plateforme pour amorcer.", fib: 1, status: "todo", deps: "T020,T038", quadrant: "do",                                                                            assignee: "aurore" },
  { id: "T104", phase: "p7", title: "Tournage 15 vidéos TikTok (3 hooks x 5 variantes)", desc: "Studio simple : phone, lumière LED, micro lavalier. Hooks : 'J'ai économisé X€', 'POV: ton banquier déteste cette app', 'Tu perds 1800€/an sans le savoir'.", fib: 8, status: "todo", deps: "T020", quadrant: "schedule",                          assignee: "aurore" },
  { id: "T105", phase: "p7", title: "5 articles SEO premiers (pillars)", desc: "Sujets : 'Comment résilier Free Mobile', 'Combien coûte une assurance habitation moyenne', 'Indemnisation vol annulé : guide 2026', 'Crédits d'impôts oubliés', 'Apps de finance perso comparées'.", fib: 5, status: "todo", deps: "", quadrant: "schedule",      assignee: "aurore" },
  { id: "T106", phase: "p7", title: "Setup newsletter (Substack ou Beehiiv)", desc: "Beehiiv recommandé : monétisation possible, design pro. Welcome series 5 emails automatiques. Premier numéro à J0 du launch.", fib: 2, status: "todo", deps: "", quadrant: "schedule",                                                                              assignee: "aurore" },
  { id: "T107", phase: "p7", title: "Identification 30 créateurs cibles (20 micro + 10 medium)", desc: "Excel : nom, plateforme, followers, engagement rate, contact, alignement. Cibler 50k-300k followers en finance/lifestyle FR.", fib: 3, status: "todo", deps: "", quadrant: "schedule",                                                          assignee: "aurore" },
  { id: "T108", phase: "p7", title: "Préparation kit créateurs (brief + assets)", desc: "PDF brief : valeurs Alfred, do's & don'ts, hooks suggérés, exemples de bons posts. Assets : logos, screenshots app, vidéos brutes utilisables.", fib: 3, status: "todo", deps: "T039,T107", quadrant: "schedule",                                          assignee: "aurore" },
  { id: "T109", phase: "p7", title: "Setup tracking publicitaire (UTM + pixels)", desc: "UTM par canal/campagne. Meta Pixel + TikTok Pixel installés. Conversions trackées (waitlist, install, abonnement).", fib: 2, status: "todo", deps: "T101", quadrant: "do",                                                                                      assignee: "aurore" },
  { id: "T110", phase: "p7", title: "Setup support client (Crisp ou Intercom)", desc: "Chat in-app + email. Auto-réponses pour questions fréquentes. Heures de réponse : <4h ouvrées au début.", fib: 3, status: "todo", deps: "", quadrant: "schedule",                                                                                                  assignee: "aurore" },
  { id: "T111", phase: "p7", title: "Création FAQ + docs aide (Notion ou Crisp)", desc: "30-50 questions courantes : sécurité, fonctionnement, tarifs, résiliation, RGPD. Search-friendly.", fib: 5, status: "todo", deps: "T110", quadrant: "schedule",                                                                                                    assignee: "aurore" },
  { id: "T112", phase: "p7", title: "Recrutement 100 bêta-testeurs (Reddit + waitlist)", desc: "Reddit (r/vosfinances, r/JeuneActif), Twitter, waitlist filtrée. Critères : ICP exact, engagés, pas concurrents. Inviter par email.", fib: 5, status: "todo", deps: "T102", quadrant: "do",                                                          assignee: "aurore" },

  // === P8 — LANCEMENT ===
  { id: "T113", phase: "p8", title: "Soft launch bêta privée (100 users)", desc: "TestFlight (iOS) + Firebase App Distribution (Android). Onboarding personnalisé. Slack ou Discord pour la communauté bêta.", fib: 5, status: "todo", deps: "T091,T112", quadrant: "do",                                                                                  assignee: "basile" },
  { id: "T114", phase: "p8", title: "Collecte feedback intensive bêta (NPS + interviews)", desc: "NPS automatique J7 et J30. 20 interviews 1-1 de 30 min. Categorisation feedback : bugs, UX, features manquantes, valeur perçue.", fib: 3, status: "todo", deps: "T113", quadrant: "do",                                                              assignee: "basile" },
  { id: "T115", phase: "p8", title: "Itération produit selon feedback bêta", desc: "Sprint de 2 semaines après collecte. Fix bugs critiques, améliore onboarding (top friction), simplifie messaging si besoin.", fib: 8, status: "todo", deps: "T114", quadrant: "do",                                                                                  assignee: "greg" },
  { id: "T116", phase: "p8", title: "Validation des unit economics initiaux", desc: "Calculer sur la cohorte bêta : % users qui économisent 30€+ en 30j, conversion free→payant, NPS, time to first value. Go/no-go avant launch public.", fib: 3, status: "todo", deps: "T114", quadrant: "do",                                                  assignee: "basile" },
  { id: "T117", phase: "p8", title: "Public launch sur App Store + Play Store", desc: "Soumission. Délais : iOS 24-72h, Android 7-14j. App Store Optimization : keywords, screenshots, description, vidéo. Premier rating ASAP.", fib: 5, status: "todo", deps: "T115", quadrant: "do",                                                              assignee: "basile" },
  { id: "T118", phase: "p8", title: "Activation Meta Ads (200€/jour, 3 creatives)", desc: "Audiences : Lookalike sur waitlist, intérêts finance/économie 25-45 ans FR. 3 creatives en A/B. Optimisation conversion (install + signup).", fib: 3, status: "todo", deps: "T109,T117", quadrant: "do",                                                  assignee: "aurore" },
  { id: "T119", phase: "p8", title: "Activation des partenariats créateurs", desc: "Contrats signés, briefs envoyés, calendrier publication coordonné (pas tout le même jour). Tracking codes promo uniques.", fib: 5, status: "todo", deps: "T108,T117", quadrant: "do",                                                                              assignee: "aurore" },
  { id: "T120", phase: "p8", title: "Lancement programme de parrainage", desc: "1 mois offert au parrain + 1 mois au filleul. Tracking via codes uniques. Limite anti-fraude. Partage facilité (lien WhatsApp).", fib: 3, status: "todo", deps: "T117", quadrant: "schedule",                                                                          assignee: "aurore" },
  { id: "T121", phase: "p8", title: "Pitch PR (Sifted, Maddyness, FrenchWeb, BFM Business)", desc: "Press release perso à chaque journaliste, pas de mass mail. Angle différencié pour chacun. Embargos coordonnés.", fib: 3, status: "todo", deps: "T117", quadrant: "schedule",                                                                  assignee: "basile" },
  { id: "T122", phase: "p8", title: "Suivi cohortes : rétention + conversion", desc: "Dashboard quotidien : D1/D7/D30 retention, conversion free→paid par cohorte, churn. Alerte si dégradation > 10%.", fib: 3, status: "todo", deps: "T061,T117", quadrant: "do",                                                                                  assignee: "basile" },

  // === P9 — V1 AUTOMATISATION ===
  { id: "T123", phase: "p9", title: "Module négociation forfaits mobile", desc: "Comparer le forfait actuel vs 5 offres marché. Si gap > 10€/mois, proposer portabilité auto (lettre + RIO). Partenariat avec courtiers (Selectra-like).", fib: 13, status: "todo", deps: "", quadrant: "do",                                                                  assignee: "greg" },
  { id: "T124", phase: "p9", title: "Module négociation assurances (auto, habitation, mutuelle)", desc: "À l'échéance annuelle, comparer + proposer changement. Loi Hamon pour résiliation. Lettres types personnalisées via Claude API. Partenariats courtiers.", fib: 13, status: "todo", deps: "", quadrant: "do",                                  assignee: "greg" },
  { id: "T125", phase: "p9", title: "Module indemnisations vols (EU 261/2004)", desc: "Détecter vols (transactions billets) → cross-référence avec API FlightStats pour annulations/retards > 3h → proposer réclamation 250-600€. Lettre type + suivi.", fib: 13, status: "todo", deps: "", quadrant: "schedule",                                  assignee: "greg" },
  { id: "T126", phase: "p9", title: "Système de commissions (tracking + 30% mois 1)", desc: "Pour chaque négociation gagnée, calculer économie mensuelle, prélever 30% du gain mois 1 sur la prochaine échéance Stripe. Transparence totale.", fib: 8, status: "todo", deps: "T071,T123", quadrant: "do",                                          assignee: "greg" },
  { id: "T127", phase: "p9", title: "LLM pour génération lettres de réclamation (Claude API)", desc: "Templates dynamiques : forfait, assurance, indemnisation vol, frais bancaires abusifs. Personnalisation contexte user. Validation humaine avant envoi (pour V1).", fib: 8, status: "todo", deps: "T123,T124,T125", quadrant: "do",          assignee: "greg" },
  { id: "T128", phase: "p9", title: "Interface human-in-loop (Retool)", desc: "Backoffice pour l'équipe ops. Voir les actions en attente de validation, réviser les lettres LLM, valider/rejeter avec un commentaire. Stats par opérateur.", fib: 5, status: "todo", deps: "T127", quadrant: "schedule",                                              assignee: "hippo" },
  { id: "T129", phase: "p9", title: "Partenariat 1 : courtier mobile (Selectra ou direct opérateur)", desc: "Négociation : commission 20-40€ par portabilité. Setup API ou flow manuel pour démarrer. Premier flux de revenus commissions.", fib: 5, status: "todo", deps: "", quadrant: "do",                                                          assignee: "basile" },
  { id: "T130", phase: "p9", title: "Partenariat 2 : courtier assurances", desc: "Réassurez-moi, Lovys, Leocare. Commissions 40-80€ par souscription. Intégration via API ou redirection.", fib: 5, status: "todo", deps: "", quadrant: "do",                                                                                                            assignee: "basile" },
  { id: "T131", phase: "p9", title: "Partenariat 3 : courtier énergie", desc: "Selectra, OVS, Papernest. Commissions 30-60€. Cycle de signature long (4-8 semaines).", fib: 5, status: "todo", deps: "", quadrant: "schedule",                                                                                                                              assignee: "basile" },
  { id: "T132", phase: "p9", title: "Module simulation what-if V1 (modèle prédictif)", desc: "Q : 'Je peux m'acheter une PS5 ?' → modèle Prophet + LLM pour répondre en langage naturel sur la base des dépenses réelles. C'est LE différenciateur produit.", fib: 21, status: "todo", deps: "T067", quadrant: "schedule",                          assignee: "greg" },
  { id: "T133", phase: "p9", title: "Module gestion couple/coloc (dépenses partagées)", desc: "User indique coloc/conjoint (sans data sharing au début). Tag transactions partagées. Calcul du 'vrai' budget perso. Critique pour 60% de l'ICP.", fib: 13, status: "todo", deps: "T067", quadrant: "schedule",                                       assignee: "greg" },
  { id: "T134", phase: "p9", title: "Module détection fraude/transactions louches", desc: "ML anomalie detection : montant inhabituel, merchant inconnu, géo improbable. Notification immédiate + action 'bloquer ma carte' (lien banque).", fib: 8, status: "todo", deps: "T068", quadrant: "schedule",                                          assignee: "greg" },
  { id: "T135", phase: "p9", title: "Module veille voyages & hôtels", desc: "User saisit dates + destination → surveillance prix Skyscanner/Booking. Alerte au creux, achat en un tap (commission affiliée).", fib: 8, status: "todo", deps: "", quadrant: "drop",                                                                                          assignee: "unassigned" },
  { id: "T136", phase: "p9", title: "Dashboard utilisateur V2 (économies + ROI)", desc: "Évolution des économies cumulées, ROI vs abonnement, breakdown par module. Preuve de valeur permanente.", fib: 5, status: "todo", deps: "T126", quadrant: "schedule",                                                                                              assignee: "hippo" },
  { id: "T137", phase: "p9", title: "Onboarding optimisé v2 (A/B test)", desc: "Tester 3 versions : long (10 écrans), court (4 écrans), avec démo sur compte fictif. Mesurer conversion onboarding completion + first action.", fib: 5, status: "todo", deps: "T080", quadrant: "schedule",                                                          assignee: "aurore" },

  // === P10 — SCALE & SÉRIE A ===
  { id: "T138", phase: "p10", title: "Recrutement CTO (si solo founder)", desc: "Profil : 8-15 ans XP, fintech ou data, leadership. 5-10% equity. Process : 30+ candidats sourcés, 10 entretiens, 2 finalistes, 1 hire.", fib: 8, status: "todo", deps: "", quadrant: "do",                                                                                  assignee: "basile" },
  { id: "T139", phase: "p10", title: "Recrutement Head of Growth", desc: "Profil : 5+ ans XP growth marketing B2C. Track record acquisition payante + organique. Maîtrise Meta, TikTok, SEO. 0,5-1% equity.", fib: 5, status: "todo", deps: "", quadrant: "schedule",                                                                                  assignee: "basile" },
  { id: "T140", phase: "p10", title: "Recrutement Data Scientist (ML)", desc: "Profil : 3-5 ans XP. Expertise détection patterns, NLP, séries temporelles. Aide à industrialiser les modèles ML détection abos + what-if.", fib: 5, status: "todo", deps: "T132", quadrant: "schedule",                                                              assignee: "basile" },
  { id: "T141", phase: "p10", title: "Recrutement Lead Designer", desc: "Profil : 5+ ans XP, mobile-first, design system. Maîtrise Figma. Idéalement portfolio fintech ou consumer apps premium.", fib: 5, status: "todo", deps: "", quadrant: "schedule",                                                                                                  assignee: "basile" },
  { id: "T142", phase: "p10", title: "Recrutement Customer Success (1-2 personnes)", desc: "Profil : empathique, écrit bien, comprend les enjeux financiers. Gère support + feedback + churn prevention.", fib: 3, status: "todo", deps: "", quadrant: "schedule",                                                                                          assignee: "basile" },
  { id: "T143", phase: "p10", title: "Recrutement Ops Légal/Compliance", desc: "Profil : juriste fintech ou compliance officer. Suit la réglementation (DSP2, AI Act, RGPD). Gère relations CNIL, ACPR.", fib: 5, status: "todo", deps: "", quadrant: "schedule",                                                                                          assignee: "basile" },
  { id: "T144", phase: "p10", title: "Programme de rétention anti-churn (cohort analysis)", desc: "Identifier signaux de churn : baisse d'engagement, peu d'économies, no-show notifications. Triggers : email perso, offre upgrade, call CS.", fib: 8, status: "todo", deps: "T122", quadrant: "schedule",                                          assignee: "aurore" },
  { id: "T145", phase: "p10", title: "Email J29 personnalisé 'économies du mois'", desc: "Auto à J29 : 'Alfred t'a économisé X€ ce mois. Voici le détail.' Réduit churn de 15-30% (benchmark Rocket Money).", fib: 3, status: "todo", deps: "T070", quadrant: "schedule",                                                                              assignee: "aurore" },
  { id: "T146", phase: "p10", title: "SEO blog : 20 articles longue traîne", desc: "Pillar + cluster strategy. Sujets : guides résiliation par opérateur, comparatifs, calculateurs. Domain authority cible 30+ en M12.", fib: 8, status: "todo", deps: "T105", quadrant: "schedule",                                                                  assignee: "aurore" },
  { id: "T147", phase: "p10", title: "Machine acquisition TikTok systémique (5 vidéos/sem)", desc: "Process : weekly briefing, batch tournage 1x/sem, edit, post. Embaucher creator/intern dédié. Outil : CapCut, Notion calendrier.", fib: 5, status: "todo", deps: "T104", quadrant: "schedule",                                                  assignee: "aurore" },
  { id: "T148", phase: "p10", title: "Scaling Meta Ads (lookalike, budget x5)", desc: "À CAC payback < 6 mois confirmé : 200€/j → 1000€/j. Audiences lookalike 1% des best customers. 5+ creatives en A/B continu.", fib: 3, status: "todo", deps: "T118", quadrant: "schedule",                                                                      assignee: "aurore" },
  { id: "T149", phase: "p10", title: "Préparation dossier Série A (data room)", desc: "Notion ou DocSend : KPIs (MRR, CAC, LTV, churn, cohorts), états financiers, contracts, équipe, roadmap, vision. Mis à jour mensuellement.", fib: 8, status: "todo", deps: "", quadrant: "do",                                                                  assignee: "basile" },
  { id: "T150", phase: "p10", title: "Création deck investisseur Série A (15-20 slides)", desc: "Structure : problème → solution → traction → marché → modèle → équipe → demande. 15 min de pitch max. Itérer 20 fois avant le 1er meeting VC.", fib: 5, status: "todo", deps: "T149", quadrant: "do",                                              assignee: "basile" },
  { id: "T151", phase: "p10", title: "Roadshow VC : 50+ meetings", desc: "Cibler : Kima, Partech, Headline, Index, Eurazeo, BPI, Frst. Process : intro warm > meeting 1 > term sheet > due diligence > closing. Délai 3-6 mois.", fib: 13, status: "todo", deps: "T150", quadrant: "do",                                                              assignee: "basile" },
  { id: "T152", phase: "p10", title: "Closing Série A (8-15M€)", desc: "Term sheet → due diligence (4-8 semaines) → SPA → closing. Avocat M&A nécessaire (2-4% des frais). Préparer la communication interne.", fib: 8, status: "todo", deps: "T151", quadrant: "do",                                                                                  assignee: "basile" },

  // === P11 — INTERNATIONAL ===
  { id: "T153", phase: "p11", title: "Localisation Belgique (DSP2 BE, partenaires locaux)", desc: "Étude réglementaire BE, partenariats agrégateur (Powens couvre BE), partenaires courtiers BE. Adaptation langue (FR-BE + NL pour V2).", fib: 13, status: "todo", deps: "", quadrant: "schedule",                                                  assignee: "unassigned" },
  { id: "T154", phase: "p11", title: "Localisation Luxembourg (fiscalité LU)", desc: "Spécificités fiscales LU. Petit marché mais haut pouvoir d'achat. Cross-frontaliers FR-LU intéressants.", fib: 8, status: "todo", deps: "T153", quadrant: "drop",                                                                                                      assignee: "unassigned" },
  { id: "T155", phase: "p11", title: "Préparation Allemagne (étude marché)", desc: "Plus gros marché EU. Concurrence forte (Finanzguru, Outbank). Étude approfondie 6 mois avant lancement. Localisation langue + fiscalité.", fib: 8, status: "todo", deps: "", quadrant: "schedule",                                                                  assignee: "unassigned" },
  { id: "T156", phase: "p11", title: "Localisation Suisse romande", desc: "Hors DSP2 (pays tiers). Partenariats agrégateurs locaux (Yapeal). Pouvoir d'achat élevé. Niche mais rentable.", fib: 5, status: "todo", deps: "", quadrant: "drop",                                                                                                              assignee: "unassigned" },
  { id: "T157", phase: "p11", title: "Module optimisation fiscale (Alfred Pro)", desc: "Crédits d'impôt, PER, frais réels, déductions oubliées. AVEC disclaimers stricts (pas de conseil réglementé). Redirection vers expert pour cas complexes.", fib: 21, status: "todo", deps: "", quadrant: "schedule",                                          assignee: "greg" },
  { id: "T158", phase: "p11", title: "Module moments de bascule (déménagement, naissance, etc.)", desc: "Détection via signaux faibles (changement IBAN, dépenses baby, etc.) → cascade d'actions auto (mutuelle, CAF, assurances, etc.).", fib: 13, status: "todo", deps: "T132", quadrant: "schedule",                                          assignee: "greg" },
  { id: "T159", phase: "p11", title: "Module RDV santé & admin (Alfred Pro)", desc: "Synchro agenda, prise de RDV (Doctolib API), rappels carte vitale. Reste niche mais haute valeur perçue pour Pro.", fib: 8, status: "todo", deps: "", quadrant: "drop",                                                                                                  assignee: "unassigned" },
];

// ═══════════════════════════════════════════════════════════════
// STYLES PARTAGÉS
// ═══════════════════════════════════════════════════════════════
export const inputStyle = {
  width: "100%", background: C.bgInput, color: C.text, border: `1px solid ${C.border}`,
  borderRadius: 6, padding: "8px 12px", fontSize: 13, outline: "none", fontFamily: "inherit",
};

export const selectStyle = {
  background: C.bgInput, color: C.text, border: `1px solid ${C.border}`,
  borderRadius: 6, padding: "8px 12px", fontSize: 13, outline: "none",
  fontFamily: "inherit", cursor: "pointer",
};

export const lblStyle = { color: C.textDim, fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", paddingTop: 8 };

// ═══════════════════════════════════════════════════════════════
// HELPERS DATE
// ═══════════════════════════════════════════════════════════════
export const todayISO = () => new Date().toISOString().slice(0, 10);

export const formatDateShort = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("fr-FR", { day: "2-digit", month: "short" });
};

export const formatDateLong = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" });
};
